### ISSUE TITLE
todo list for version 1.0.0

### ISSUE THREAD

**Issue by sebkopf** [KopfLab/ggstackplot#2]
In this thread add any todo items for getting version 1.0.0 ready to submit to cran

- [x] implement vertically stacked plots
- [x] implement horizontally stacked plots
- [x] address all bugs/features for [version 1.0.0 milestone](/kopflab/ggstackplot/milestone/1)
- [ ] write unit tests to increase code coverage to > 80% [![codecov](https://codecov.io/gh/kopflab/ggstackplot/branch/main/graph/badge.svg?token=SN0YDIJ6Y6)](https://app.codecov.io/gh/kopflab/ggstackplot)
- [x] make sure RMD check passes for al operating system [![R-CMD-check](https://github.com/KopfLab/ggstackplot/actions/workflows/R-CMD-check.yaml/badge.svg)](https://github.com/KopfLab/ggstackplot/actions/workflows/R-CMD-check.yaml)
- [x] document all functions thoroughly
- [x] write vignette to demonstrate all functionality (simple and advanced examples) with easily available data (e.g. `mtcars`), features to document (not an exhaustive list)
  - [x] basic plot stacking in x and y
  - [x] using tidyselect syntax to change x/y axis labels
  - [x] changing colors
  - [x] changing overlap
  - [x] changing axis positioning
  - [x] using the `template` to add geoms
  - [x] using the `template` to modify scales
  - [x] using the `template` to modify themes
  - [x] using the `template` to add other aesthetics (e.g. linetype)
  - [x] using the `template` and `geom_...(data = ...)` to show geoms in different panels
- [ ] write vignette(s) to demonstrate functionality with real data (ideally paleo or oceanography data)
- [x] make sure documentation is up to date and properly rendered https://ggstackplot.kopflab.org/
- [x] make sure package metadata is complete (authors, description, etc.)
- [x] update lifecycle to stable [![Lifecycle: experimental](https://img.shields.io/badge/lifecycle-experimental-orange.svg)](https://lifecycle.r-lib.org/articles/stages.html#experimental)

First release:

* [x] `usethis::use_cran_comments()`
* [ ] Update (aspirational) install instructions in README
* [x] Proofread `Title:` and `Description:`
* [x] Check that all exported functions have `@return` and `@examples`
* [x] Check that `Authors@R:` includes a copyright holder (role 'cph')
* [x] Check [licensing of included files](https://r-pkgs.org/license.html#code-you-bundle)
* [x] Review <https://github.com/DavisVaughan/extrachecks>

Prepare for release:

* [ ] `git pull`
* [ ] Check if any deprecation processes should be advanced, as described in [Gradual deprecation](https://lifecycle.r-lib.org/articles/communicate.html#gradual-deprecation)
* [x] `urlchecker::url_check()`
* [x] `devtools::check(remote = TRUE, manual = TRUE)`
* [x] `devtools::check_win_devel()`
* [x] `rhub::check_for_cran()`
* [ ] `git push`
* [ ] Draft blog post

Submit to CRAN:

* [ ] `usethis::use_version('major')`
* [ ] `devtools::submit_cran()`
* [ ] Approve email

Wait for CRAN...

* [ ] Accepted :tada:
* [ ] `git push`
* [ ] `usethis::use_github_release()`
* [ ] `usethis::use_dev_version()`
* [ ] `usethis::use_news_md()`
* [ ] `git push`
* [ ] Tweet / advertize

**Comment by sebkopf** [comment]
i'm working on the `address all bugs/features` part

**Comment by JmMcFarlin** [comment]
I'm working on a vignette w/ some published paleoclimate data

**Comment by sebkopf** [comment]
thanks for all the work on documenting features and adding real data example @tacaro (and catching two more important bugs :) - now we just need a few more examples (@JmMcFarlin / @rabergj ?) :) and we're ready for CRAN 🚀
